<img style="float: center; width: 100%" src="https://raw.githubusercontent.com/andrejkk/TalksImgs/master/FrontSlideUpperBan.png">
<p style="margin-bottom:2cm;"></p>

<center>
    <H1> 9. Markov chains </H1>
   


<br><br>
    <H3> Andrej Košir, Lucami, FE </H4>
    
    <H4> Kontakt: prof. dr. Andrej Košir, andrej.kosir@lucami.fe.uni-lj.si, skype=akosir_sid </H4>
</center>


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 1 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Intro

- Goals: 
    - Markov chain modeling
    - Markov chain state analysis 
- Stochastic process on finite states, most useful and used. We limit to:
    - Discrete times
    - Discrete state space (finite or countably many states)
- Case: user behavior
- Usage
    - Finite state machine analysis: software, TC system, ...
    - Models in economy
- What are questions:
    - Distributions of visits
    - Long term behavior
    - Absorption of states



<figure>
<img style="float: center; width: 300px; margin: 0px 20px 20px 0px;" src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/MarkovChain_Emotions.png">
  <figcaption></figcaption>
</figure>

<figure>
<img style="float: right; width: 200px; margin: -320px 20px 20px 0px;" src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/MarkovChain_Marker.png">
  <figcaption></figcaption>
</figure>


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 2 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Sections 


9.1. Definition, basic characteristics

■ Markov chain definition $\large{*}$

■ Transition matrix, distribution of states $\large{*}$


9.2. Classification of states

■ Communication of states and period $\large{*}$

■ Recurrent and transient state $\large{*}$

■ Ergodic Markov chain and return times

■ Stationary (limit) distribution $\large{*}$
 
■ Finite Markov chain $\large{*}$


9.3. Transition matrix estimation

■ Transition probability estimation

■ Confidence intervals and quantiles

■ Sample size determination

■ Numerical aspect

■ Case: telecommunication service user modeling



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 3 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## 9.1. Definition, basic characteristics

■ Markov chain definition

■ Transition matrix, distribution of states



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 4 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Markov chain definition


- State space $S$, $m=|S|$
    - Finite, countable, continuous


- Time $T$
    - Discrete, continuous


- Stochastic process: 
$$ X_n : T \to S $$


- Discrete Markov chain is a discrete time discrete space Markov chain having Markov property
$$ P[X_{n+1}|_{X_n, X_{n-1}, \ldots, X_0}] = P[X_{n+1}|_{X_n}] = P[X_1|_{X_0}] $$


- Transition probability of one step
$$ p_{ij} = P[X_{n+1}=j|_{X_n=i}] $$


- Finite state space means there is a matrix  of transition probabilities
$$ P = [p_{ij}], \; i,j\in S. $$
    - Row sums are equal to 1. 



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 5 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

In [2]:
import numpy as np
from sympy import Matrix
from sympy.functions import re

# Case 1 
# Transition matrix
P = np.array([[0.7, 0.2, 0.1, 0.0], 
              [0.2, 0.5, 0.2, 0.1], 
              [0.05, 0.15, 0.6, 0.2], 
              [0.0, 0.2, 0.0, 0.8]])

## ■ Transition matrix, distribution of states



- Transition matrix for $n$ steps
    - $p_{ij}^{(n)} = P[X_{k+n}|_{X_k=i}]$, $P^{(n)}=[p_{ij}^{(n)}]$
    - From total probability formula
    $$ P^{(n)} = P^n $$
    

- Distribution of states: 
$$ \pi_i^n = P[X_n=i], \pi^n = [\pi_1^n, \ldots, \pi_i^n] $$
    - Initial distribution: $\pi^0$. If initial state $X_0=i_0$ is known
    $$ \pi^0=\delta_{i_0 i} $$
    - From total probability formula:
    $$ \pi^n = P^{(n)} \pi^0 $$
    - More on limit distribution later



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 6 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## 9.2. Classification of states


■ Communication of states and period

■ Recurrent and transient state

■ Ergodic Markov chain and return times

■ Stationary (limit) distribution

■ Finite Markov chain



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 7 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Communication of states and period


- Accessible state
    - State $j$ is accessible from state $i$ if $\exists n: p_{ij}^{(n)}>0$. Notation $i\leftrightarrow j$
    - Two states communicate if $i\rightarrow$ and $i \leftarrow j$, denoted by $i\leftrightarrow j$
    - „Communicate“ is equivalent relation


- Markov chain is irreducible if there are only one single communicating class


- Period of state $i$ ia denoted by $d(i)$ is greatest common divisor of all $n$ such that $P_{ii}^{(n)} > 0$:  
    - If $i\leftrightarrow j$ then $d(i) = d(j)$;
    - State is aperiodic if $d(i)=1$;



- State $i$ is zero state if 
$$ \lim_{n\to\infty} P_{ii}^{(n)} = 0. $$


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 8 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

In [3]:
# ---------------------------------------------------------------------------------------------------
# Classification of states
print ('Transition matrix P=\n', P)
print ('\nTransition matrix P^2=\n', np.linalg.matrix_power(P, 2))

# All entries of P^2 are non-zero
# => All atates are connected

Transition matrix P=
 [[0.7  0.2  0.1  0.  ]
 [0.2  0.5  0.2  0.1 ]
 [0.05 0.15 0.6  0.2 ]
 [0.   0.2  0.   0.8 ]]

Transition matrix P^2=
 [[0.535 0.255 0.17  0.04 ]
 [0.25  0.34  0.24  0.17 ]
 [0.095 0.215 0.395 0.295]
 [0.04  0.26  0.04  0.66 ]]


In [3]:
# ---------------------------------------------------------------------------------------------------
# Decompose transition matrix
# Use Jordan decomposition
#mP = Matrix(P)
#mB, mJ = mP.jordan_form()
#B, J = np.array(mB), np.array(mJ)
B = np.array([[-0.5,-0.776313,0.659526,-0.413722],
              [-0.5,-0.212847,-0.11514,0.830469],
              [-0.5,0.283275,-0.73692,-0.123153],
              [-0.5,0.521335,0.0933625,-0.352121]])
J = np.array([[1.,0,0,0],
              [0,0.718345,0,0],
              [0,0,0.553349,0],
              [0,0,0,0.328305]])

# Test decomposition
err_mat = P - np.dot(B, np.dot(J, np.linalg.inv(B)))
print ('\nDecomposition error norm = ', np.linalg.norm(err_mat))


Decomposition error norm =  7.249920892047682e-07


## ■ Recurrent and transient state


- Probability of return after exactly $n$ steps
$$ f_{ij}^n = P[X_n=j|_{X_{n-1}\ne j, \ldots, X_1\ne j, X_0=i}] $$


- Random variable of transitions from $i$ to $j$ is denoted by $T_{i}$ and its distribtion is 
$$ T_{ij} \sim \left(\matrix{0 & 1 & 2 & \ldots \cr f_{ij}^0 & f_{ij}^1 & f_{ij}^2 & \ldots}\right) $$
    - Denote $T_i = T_{ii}$
    - Denote $\sum_{n=0}^\infty f_{ii}^n = f_{ii}^*$. Value 
    $$ 1 - f_{ii}^* $$
    is a probability that Markov Chain newer returns to state 𝑖 after leaving it. 


- State $i$ is **recurrent** if $f_{ii}^* = 1$. State is **transient** if it is not recurrent.
    - Recurrence and transience are communicating class properties


- We have: state $i$ is recurrent if and only if
$$ \sum_{n=1}^\infty P_{ii}^{(n)} = \infty $$

- Also: if $i\leftrightarrow j$ then both states are either transient or recurrent  



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 9 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

In [4]:
# Recurent, transient? 

# Eigenvalues
eigVals, eigVecs = np.linalg.eig(P.T)

# Get it sorted
idx = eigVals.argsort()[::-1]   
eigVa = eigVals[idx]
eigVc = eigVecs[:,idx]

las_bf =  (1./(1-eigVa[1:4]))-1
print ('las_bf', las_bf)
           
sumJn = np.diag(np.insert(las_bf, 0, np.inf))
print ('\nSum J^n\n', sumJn)

sumPn = np.dot(B, np.dot(sumJn, np.linalg.inv(B)))
print ('\nSum P^n\n', sumPn)

# Since all diagonal elements of sum P^n are infinity
#  => all states are recurrent

las_bf [2.55044912 1.23888596 0.48877142]

Sum J^n
[[       inf 0.         0.         0.        ]
 [0.         2.55044912 0.         0.        ]
 [0.         0.         1.23888596 0.        ]
 [0.         0.         0.         0.48877142]]

Sum P^n
[[inf inf inf inf]
 [inf inf inf inf]
 [inf inf inf inf]
 [inf inf inf inf]]


In [5]:
def inf_sum(a_lst):
    return [(la/(1.0-la) if la < 1 else np.infty) for la in a_lst]

# ---------------------------------------------------------------------------------------------------
# Are states recurrent?
# Compute sum of P^n
sumJ = np.diag(inf_sum(np.diag(J)))
sumP = np.dot(B, np.dot(sumJ, np.linalg.inv(B)))

print ('\nSum of P^n = \n', sumP)
# => All states are reccurent 


Sum of P^n = 
[[inf inf inf inf]
 [inf inf inf inf]
 [inf inf inf inf]
 [inf inf inf inf]]


## ■ Ergodic Markov chain and return times


- Markov chain is **Ergodic** if it is 
    - Irreducible
    - Recurrent (all states are recurrent)
    - Aperiodic (all states are aperiodic)
    - Nonzero (all states are positive)
    
    
- Expected return time: 
$$ E(T_i) = \sum_{n=0}^\infty n f_{ii}^{(n)} $$


- In ergodic Markov chain
$$ \lim_{n\to\infty} P_{ii}^{(n)} = \frac{1}{E(T_i)} $$
$$ \lim_{n\to\infty} P_{ij}^{(n)} = \lim_{n\to\infty} P_{ii}^{(n)} $$ 


- Recurrent **zero** state $i$:
$$ \lim_{n\to\infty} P_{ii}^{(n)} = 0 \; \Leftrightarrow \;  E(T_i) = \infty  $$


- Recurrent **positive** = **ergodic** state $i$: 
$$ \lim_{n\to\infty} P_{ii}^{(n)} > 0 \; \Leftrightarrow \; E(T_i) < \infty  $$



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 10 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

In [6]:
def inf_lim(a_lst):
    return [(0 if la < 1 else 1) for la in a_lst]

# ---------------------------------------------------------------------------------------------------
# Zero or positive states?
# Compute lim of P^n
limJ = np.diag(inf_lim(np.diag(J)))
limP = np.dot(B, np.dot(limJ, np.linalg.inv(B)))

print ('\nlim of P^n = \n', limP)

# Since all lim P^n are positive
# => all states are positive

# Expected times of visits
ETi = 1.0/np.diag(limP)

print ('\nExpected number of visits py states:\n', ETi)


lim of P^n = 
[[0.21301781 0.27218919 0.18934915 0.32544385]
 [0.21301781 0.27218919 0.18934915 0.32544385]
 [0.21301781 0.27218919 0.18934915 0.32544385]
 [0.21301781 0.27218919 0.18934915 0.32544385]]

Expected number of visits py states:
[4.69444311 3.67391519 5.28124903 3.07272668]


## ■ Stationary (limit) distribution


- State distribution after $n$ steps 
$$ \pi_i^n = P[X_n=i], \qquad \pi^n = [\pi_1^n, \ldots, \pi_i^n] $$


- Stationary (limit) distribution: 
  $$ \pi = \lim_{n\to\infty} \pi^n $$
    - When uniquely defined: when all states are recurrent positive


- Ergodic MC: stationary distribution exists
- Stationary distribution of ergodic MC chain is left eigenvector of transition matrix: 
  $$ \pi^\top = \pi^\top P. $$


- Note: in an ergodic MC a stationary distribution independent of initial distribution $\pi^0$.



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 11 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

In [7]:
# ---------------------------------------------------------------------------------------------------
# Limit distribuion
eigVals, eigVecs = np.linalg.eig(P.T)
pi = eigVecs[:, 0]/sum(eigVecs[:, 0])

print ('\neigVals=\n', eigVals)
#print '\neigVecs=\n', eigVecs
print ('\nLimit distribution =', pi)


eigVals=
[1.         0.32830522 0.71834549 0.55334929]

Limit distribution = [0.21301775 0.27218935 0.18934911 0.32544379]


## ■ Probability of absorption


- Absorption: chain never leave a subset of states $S_0 \subset S$


- What is the probability of absorption?


- If a chain starts in transient state, then either:
    1. It leaves a set of transient states with probability of 1
    2. It enters a set of recurrent states with probability of 1


- Absorbing states $i$: the only state of an absorbing state
We have: $i$ absorbing if and only if 
$P_{ii}=1$


- Let $i\in S$ be a transient state, $S_e$ a set of recurrent states:<br>
Probability of absorption: $\pi_i(S_e)$ is the probability MC with $X_0=i$ gets absorbed into the set of states $S_e$


- We have
$$ \lim_{n\to\infty} P_{ij}^{(n)} = \pi_i(S_e)\pi_j. $$



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 12 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Finite Markov chain


- Finite number of states $|S|=m < \infty$.


- Each finite MC has recurrent states!


- All recurrent states are positive, that is ergodic and has finite expected return time
$$ \lim_{n\to\infty} P_{ii}^{(n)} > 0. $$


- Classification of states: all states are $S=S_m\cup S_e$, where
    - Transient states: $S_m$
    - Ergodic states: $S_e$
    
    
- Transient matrix is of a block form:
    - Ergodic states: $1, \ldots, m-K$
    - Transient state: $m-K+1, \ldots, m$
    $$ P = \left[\matrix{S & 0 \cr R & Q}\right] $$

- Fundamental matrix:
$$ N = (I - Q)^{-1}.  $$



   
<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 13 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

In [3]:
# Case 2
c2P = np.array(
    [[0.7, 0.3, 0.0, 0.0], 
     [0.2, 0.8, 0.0, 0.0], 
     [0.05, 0.15, 0.6, 0.2], 
     [0.0, 0.2, 0.0, 0.8]])

print ('Transition matrix P=\n', c2P)


Transition matrix P=
 [[0.7  0.3  0.   0.  ]
 [0.2  0.8  0.   0.  ]
 [0.05 0.15 0.6  0.2 ]
 [0.   0.2  0.   0.8 ]]


In [4]:
# ---------------------------------------------------------------------------------------------------
# Classification of states
print ('Transition matrix P=\n', c2P)
print ('\nTransition matrix P^2=\n', np.linalg.matrix_power(c2P, 2))
print ('\nTransition matrix P^3=\n', np.linalg.matrix_power(c2P, 3))

# Matrix multiplications by blocks
# => 2 x 2 block of zeros stayes the same
# => There are two connected classes of states

Transition matrix P=
 [[0.7  0.3  0.   0.  ]
 [0.2  0.8  0.   0.  ]
 [0.05 0.15 0.6  0.2 ]
 [0.   0.2  0.   0.8 ]]

Transition matrix P^2=
 [[0.55  0.45  0.    0.   ]
 [0.3   0.7   0.    0.   ]
 [0.095 0.265 0.36  0.28 ]
 [0.04  0.32  0.    0.64 ]]

Transition matrix P^3=
 [[0.475  0.525  0.     0.    ]
 [0.35   0.65   0.     0.    ]
 [0.1375 0.3505 0.216  0.296 ]
 [0.092  0.396  0.     0.512 ]]


In [5]:
# ---------------------------------------------------------------------------------------------------
# Limit distribuion
eigVals, eigVecs = np.linalg.eig(c2P.T)


# Get it sorted
idx = eigVals.argsort()[::-1]   
eigenValues = eigVals[idx]
eigenVectors = eigVecs[:,idx]

# Normalize eigenvector
pi = eigenVectors[:, 0]/sum(eigenVectors[:, 0])

print ('\neigVals=\n', eigenValues)
#print '\neigVecs=\n', eigenVectors
print ('\nLimit distribution =', pi)


eigVals=
 [1.  0.8 0.6 0.5]

Limit distribution = [ 0.4  0.6 -0.  -0. ]


In [7]:
# ---------------------------------------------------------------------------------------------------
# Decompose transition matrix
# Use Jordan decomposition
#mP = Matrix(c2P)
#mB, mJ = mP.jordan_form()
#B, J = np.array(mB), np.array(mJ)
c2B = np.array([[1.0, 0, 0, 9.0/4],
              [1.0, 0, 0, -3.0/2],
              [1.0, 1.0, 1.0, -7.0/8],
              [1.0, 1.0, 0, 1.0]])
c2J = np.array([[1.0,0,0,0],
              [0,4.0/5,0,0],
              [0,0,3.0/5,0],
              [0,0,0,1.0/2]])

# Test decomposition
err_mat = c2P - np.dot(c2B, np.dot(c2J, np.linalg.inv(c2B)))
print ('\nDecomposition error norm = ', np.linalg.norm(err_mat))


Decomposition error norm =  1.9675159943996247e-16


In [8]:
def prd(a,b):
    if np.isinf(a) and b == 0:
        return 0
    if np.isinf(b) and a == 0:
        return 0
    return a*b

def myDot(A,B):
    nA1, nA2, nB2 = A.shape[0], A.shape[1], B.shape[1]
    AB = np.zeros((nA1,nB2))
    for i in range(nA1):
        for j in range(nB2):
            curr = 0
            for k in range(nA2):
                curr += prd(A[i,k], B[k,j])
            AB[i, j] = curr
    return AB

# Classification of states
# Recurent, transient? 

# Eigenvalues
eigVals, eigVecs = np.linalg.eig(c2P.T)

# Get it sorted
idx = eigVals.argsort()[::-1]   
eigVa = eigVals[idx]
eigVc = eigVecs[:,idx]

las_bf =  (1./(1-eigVa[1:4]))-1
sumJn = np.diag(np.insert(las_bf, 0, np.inf))

sumPn = myDot(c2B, myDot(sumJn, np.linalg.inv(c2B)))
print ('\nSum P^n\n', sumPn)

# Since diagonal elements of sum P^n i=1 and i=2 are infinity
#  => states i=1 and i=2 are recurrent
# Since diagonal elements of sum P^n i=3 and i=4 are finite
#  => states i=3 and i=4 are transient



Sum P^n
 [[inf inf 0.  0. ]
 [inf inf 0.  0. ]
 [inf inf 1.5 2.5]
 [inf inf 0.  4. ]]


In [9]:
def inf_lim(a_lst):
    return [(0 if la < 1 else 1) for la in a_lst]

# ---------------------------------------------------------------------------------------------------
# Zero or positive states?
# Compute lim of P^n
limJ = np.diag(inf_lim(np.diag(c2J)))
limP = np.dot(c2B, np.dot(limJ, np.linalg.inv(c2B)))

print ('\nlim of P^n = \n', limP)

# Since all lim P^n are positive
# => all states are positive

# Expected times of visits
ETi = 1.0/np.diag(limP)

print ('\nExpected number of visits py states:\n', ETi)



lim of P^n = 
 [[0.4 0.6 0.  0. ]
 [0.4 0.6 0.  0. ]
 [0.4 0.6 0.  0. ]
 [0.4 0.6 0.  0. ]]

Expected number of visits py states:
 [2.5        1.66666667        inf        inf]


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:16: RuntimeWarning: divide by zero encountered in true_divide


In [14]:
# ---------------------------------------------------------------------------------------------------
# Limit distribuion
eigVals, eigVecs = np.linalg.eig(c2P.T)


# Get it sorted
idx = eigVals.argsort()[::-1]   
eigenValues = eigVals[idx]
eigenVectors = eigVecs[:,idx]

# Normalize eigenvector
pi = eigenVectors[:, 0]/sum(eigenVectors[:, 0])

print ('\neigVals=\n', eigenValues)
#print '\neigVecs=\n', eigenVectors
print ('\nLimit distribution =', pi)


eigVals=
[1.  0.8 0.6 0.5]

Limit distribution = [ 0.4  0.6 -0.  -0. ]


## ■ Number of visits of a transient state


- Random variable $n_i$: number of visits of a state $i$ in an arbitrary long time


- Expected number of visits of a state $j$ if initial state is $𝑖$: 
 $$ E_i[n_j] < \infty $$

- We have: if state $i$ is transient: 
$$ E_i[n_j] = \sum_{k=1}^\infty P_{ij}^{(k)} $$

- Also - fundamental matrix gives expected values:
$$ \left[E_i[n_j]\right] = N $$ 




<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 14 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

In [15]:
# Expected number of visits of recurent states
m = 4 # |S|
K = 2 # number of recurent states

Q = c2P[K:m, K:m]
print ('Part of transition matrix Q = \n', Q)

N = np.linalg.inv(np.eye(m-K)-Q)
print ('\nFundamental matrix N =\n', N)

Part of transition matrix Q = 
[[0.6 0.2]
 [0.  0.8]]

Fundamental matrix N =
[[2.5 2.5]
 [0.  5. ]]


## 9.3 Transition matrix estimation


■ Transition probability estimation

■ Confidence intervals and quantiles

■ Sample size determination

■ Numerical aspect

■ Case: telecommunication service user modeling


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 15 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Transition probability estimation

- Transition probability 
$$ p_{ij} = \frac{n_k}{n} $$
is a statistical estimation;


- Parameter estimation
    - estimate and termine
        - expected value $\overline{x}$
        - standard deviation $\sigma$
        - for a selected risk level $\alpha$ compute $z_\alpha$ (if normal distribution $z_{0.05}=1.96$)
    - Confidence interval: 
$$ CI = [\overline{x} - z_\alpha\frac{\sigma}{\sqrt{n}}, \overline{x} + z_\alpha\frac{\sigma}{\sqrt{n}}] $$
    - Sample size: determined from a preset confidence interval length 
    $$ |CI| = 2 z_\alpha\frac{\sigma}{\sqrt{n}} $$




<img style="float: right; width: 250px; margin: 0px 20px 20px 0px;" src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/EstimationConfInterval.png">



<p style="margin-bottom:7cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 16 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Confidence intervals and quantiles


- Confidence interval visualization


<img style="float: center; width: 350px; margin: 0px 20px 20px 0px;" src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/EstimationConfIntervalVsSampleSize.png">


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 17 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Transition matrix estimation sample size determination


- From confidence interval size


- Confidence interval for risk level $\alpha=0.05$ ($z_\alpha=1.96$)
$$ CI = [p_0 - z_\alpha\sqrt{p_0(1-p_0)/n}, p_0 + z_\alpha\sqrt{p_0(1-p_0)/n}] $$


For $p=0.65$ and $|CI|=\Delta p$ at $\alpha=0.05$
$$ n\geq \frac{4 z_\alpha^2}{\Delta p^2} p_0 (1-p_0) $$
we get
 - for $\Delta p=0.01:$ $n\geq 34959$,
 - for $\Delta p=0.02:$ $n\geq 175$,
 - for $\Delta p=0.04:$ $n\geq 88$.
 


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 18 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Numerical aspect of transition matrix computation


- We need matrix power 
$$ P^n = P^{(n)} $$


- Jordan decomposition
$$ P = B J B^{-1},  $$
where $J$ is Jordan canonical form. 


- For each class of states we have
$$ J = \lambda I + R $$
and 
$$ P^n = B J^n B^{-1} $$

<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 19 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Case: telecommunication service user modeling


- A set of telecommunication users $U$


- We split them into classes: $U=U_1 \cup U_2 \cup U_3 \cup U_4$
    - Very satisfied: $U_1$
    - Satisfied: $U_2$
    - Not satisfied: $U_3$
    - Churners: $U_4$


- Initial distribution: estimation of users

- Results:
    - Recurrent - transients states
    - Stationary distribution



<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 20 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## ■ Conclusion


- Most useful: finite Markov chain
- Check the transition matrix assumption: stationarity 


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 21 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">