<img style="float: center; width: 100%" src="https://raw.githubusercontent.com/andrejkk/TalksImgs/master/FrontSlideUpperBan.png">
<p style="margin-bottom:2cm;"></p>

<center>
    <H1> Matrični račun za Markovske verige </H1>
   


<br><br>
    <H3> Andrej Košir, Lucami, FE </H4>
    
    <H4> Kontakt: prof. dr. Andrej Košir, andrej.kosir@lucami.fe.uni-lj.si, skype=akosir_sid </H4>
</center>


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 1 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

<div style="display:flex;font-weight:bold;font-size:0.9em;">
<div style="flex:1;width:50%;"> 9. Markovske verige  </div>
<div style="flex:1;width:50%;text-align:right;"> Cilji </div>
</div>

$\def\l{{\lambda}}$


## Uvod

Večji del lastnosti stanj in obnašanja Markovske verige ugotavljamo iz prehodne matrike $n$ korakov $P^{(n)}$. Pri tem za določitev ničelnosti stanj določimo vrednost limite
$$ \lim_{n\to\infty} P^{(n)} $$
in za minljivost oz. povrnljivost določimo vrednost vsote
$$ \sum_{n=1}^\infty P^{(n)}.  $$

Vzemmimo, da ima Markovska matrika končno stanje $|S|=m$. Ker je prehodna matrika $n$ korakov $P^{(n)}$ enaka navadni potenci prehodne matrike enega koraka $P$, torej $P^{(n)} = P^n$, je učinkovito računanje potenc prehodne matrike nujno za klasifikacijo stanj markovske verige. Pri tem uporabimo Jordanov matrični razcep. 

Dodajmo še, da so lastne vrednosti $\lambda_i$, $i=1,\ldots,m$ prehodne matrike $P$ realne, manjše ali enake $1$ in največka od njih je enaka $1$.  
<br>
<br>


## Jordanov matrični razcep in potenca matrike


Kvadratno prehodno matriko $P$ je mogoče razcepit kot
$$ P = B . J . B^{-1}, $$
kjer je $J$ Jordanova matrika in $B$ obrnljiva matrika. Tedaj lahko npr. tretjo potenco matrike $P$ zardi asociativnosti množenja matrik izračunamo kot
$$
\begin{eqnarray*}
 P^3 & = & (B . J . B^{-1}).(B . J . B^{-1}).(B . J . B^{-1}) \\
     & = & B . J . (B^{-1}.B) . J . (B^{-1}.B) . J . B^{-1}) \\
     & = & B . J^3 . B^{-1}
\end{eqnarray*}
$$


Na podoben način za poljubno potenco $n$ dobimo
$$ P^n = B . J^n . B^{-1} $$


Če so lastne vrednosti prehodne matrike $P$ različne (to ni nujno res, v praktičnih primerih navadno je res), je Jordanova matrika J diagonalna oblike 
$$ J  = 
\begin{bmatrix}
\l_1 & 0 & \cdots & 0\\
0 & \l_2 & \ldots & 0  \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \l_m 
\end{bmatrix} $$


Neposredno preverimo, da je njena $n$-ta potenca enaka
$$ J^n  = 
\begin{bmatrix}
\l_1^n & 0 & \cdots & 0\\
0 & \l_2^n & \ldots & 0  \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \l_m^n 
\end{bmatrix} $$


Upoštevamo obe zgornji ugotovitvi in $n$-to potenco prehodno matrike $P$ lahko zapišemo kot
$$ P^n  = B . 
\begin{bmatrix}
\l_1^n & 0 & \cdots & 0\\
0 & \l_2^n & \ldots & 0  \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \l_m^n 
\end{bmatrix} 
. B^{-1}. $$
Ta izraz je primeren za klasifikacijo stanj Markovske verige. 


<!--
<figure>
<img style="float: right; width: 200px; margin: -320px 20px 20px 0px;" src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/MarkovChain_Marker.png">
  <figcaption></figcaption>
</figure>
-->

<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 2 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

## Klasifikacija stanj Markovske verige

V tem poglavju bomo z uporabo Jordanovega razcepa pripravili orodje za klasifikacijo stanj markovske verige. 

### Ničelno in neničelno stanje

Ničelnost oziroma neničelnost stanja določimo z vrednotenjem izraza
$$ \lim_{n\to\infty} P^{(n)} $$,
torej limite diagonalnih elementov matrik $P^{(n)}$, ki je enaka $P^{n}$. Pri tem na naslednji način uporabimo uporabimo Jordanov razcep:
$$
\begin{eqnarray*}
 \lim_{n\to\infty} P^{(n)} & = & \lim_{n\to\infty} P^{n} = \lim_{n\to\infty} B. J^{n}.B^{-1} \\
   & = & B. \left(\lim_{n\to\infty}J^{n}\right).B^{-1} \\
   & = & B. \begin{bmatrix}
    \lim_{n\to\infty} \l_1^n & 0 & \cdots & 0\\
    0 & \lim_{n\to\infty} \l_2^n & \ldots & 0  \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots & \lim_{n\to\infty} \l_m^n 
    \end{bmatrix}.B^{-1}
   & = & B. \begin{bmatrix}
    1 & 0 & \cdots & 0\\
    0 & 0 & \ldots & 0  \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots & 0 
    \end{bmatrix}.B^{-1}
\end{eqnarray*}
$$

V zgornjem izračunu smo upoštevali, da je lahko zamenjamo vrstni red limite in matričnega množenja. Poleg tega upoštevamo, da velja $\l_1=1$ in $\l_i<1$ za $i=2,\ldots, m$ in da je $\lim_{n\to\infty} q^n$ enaka $1$ za $q=1$ in $0$ za $0\leq q<1$. 

Iz dobljene matrike torej preberemo diagonalne elemente in stanja $i$, za katere je diagonalni elemet enak $0$, so ničelna, za tsta stanja $i$, za katera je diagonalni element večji od nič, so neničelna oziroma pozitivna. Primer analize v naslednji celici. 


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 3 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

In [2]:
import numpy as np


# Transition matrix
# matP = {{0.7, 0.15, 0.1, 0.05}, {0.2, 0.5, 0.2, 0.1}, {0.05, 0.15, 0.6, 0.2}, {0.0, 0.0, 0.0, 1}}
P = np.array([[0.7, 0.15, 0.1, 0.05], 
              [0.2, 0.5, 0.2, 0.1], 
              [0.05, 0.15, 0.6, 0.2], 
              [0.0, 0.0, 0.0, 1]])

In [42]:
# Jordan Decomposition

B = np.array([[1, 0.515196, -0.949901, 1.63471],
[1, -1.90109, 0.13712, 1.36397],
[1, 1, 1, 1],
[1, 0, 0, 0]])

J = np.array([[1, 0, 0, 0],
[0, 0.340597, 0, 0],
[0, 0, 0.573073, 0],
[0, 0, 0, 0.88633]])

print('Decomposition error = ', np.linalg.norm(P - B @ J @ np.linalg.inv(B)))

Decomposition error =  1.0210222343932876e-06


In [43]:
# Zero or positive states? 

m = 4
limJn = np.zeros((m,m))
limJn[0,0] = 1.0

print ('$Limit of the matrix = \n', B @ limJn @ np.linalg.inv(B))

# Conclusion: all diagonal elements are equal to 0 (there are some numerical errors)

$Limit of the matrix = 
 [[4.16333634e-17 0.00000000e+00 1.38777878e-17 1.00000000e+00]
 [4.16333634e-17 0.00000000e+00 1.38777878e-17 1.00000000e+00]
 [4.16333634e-17 0.00000000e+00 1.38777878e-17 1.00000000e+00]
 [4.16333634e-17 0.00000000e+00 1.38777878e-17 1.00000000e+00]]


### Povrnljivo in minljovo stanje 

Za določitev minljivosti oz. povrnljivosti določimo diagonalen vrednosti vsote
$$ \sum_{n=1}^\infty P^{(n)}.  $$

Tudi tu si pomagamo z Jordanovim razcepom. Matrika $P^{(n)}$ je enaka matriki $P^{n}$ in velja:
$$
\begin{eqnarray*}
 \sum_{n=1}^\infty P^{(n)} & = & \sum_{n=1}^\infty P^{n} = \sum_{n=1}^\infty B. J^{n}.B^{-1} \\
   & = & B. \left(\sum_{n=1}^\infty J^{n}\right).B^{-1} \\
   & = & B. \begin{bmatrix}
    \sum_{n=1}^\infty \l_1^n & 0 & \cdots & 0\\
    0 & \sum_{n=1}^\infty \l_2^n & \ldots & 0  \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots & \sum_{n=1}^\infty \l_m^n 
    \end{bmatrix}.B^{-1}
   & = & B. \begin{bmatrix}
    \infty & 0 & \cdots & 0\\
    0 & \frac{1}{1-\l_2}-1 & \ldots & 0  \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots & \frac{1}{1-\l_m}-1 
    \end{bmatrix}.B^{-1}
\end{eqnarray*}
$$

Pri zgornjem izračunu smo upoštevali, da vrstni red konvergentne vsote in matričnega množenja lahko zamenjamo. Upoštevali smo tudi, da je $\sum_{n=1}^\infty q^n$ enako $\infty$ za $q=1$ in $\frac{1}{1-q}-1$.


<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 2 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">

In [49]:
# Recurrent or transient states? 

las_bf =  (1./(1-np.diag(J)[1:4]))-1
sumJn = np.diag(np.insert(las_bf, 0, np.inf)) # Sum of J^n

sumPn = B @ sumJn @ np.linalg.inv(B) # Sum of P^n

print ('Summated matrix = \n', sumPn)

# Conclussion: all diagonal elements are infinite (secong column is a numerical error) and therefore all states are recurrent. 

Summated matrix = 
 [[inf nan inf inf]
 [inf nan inf inf]
 [inf nan inf inf]
 [inf nan inf inf]]


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:6: RuntimeWarning: invalid value encountered in matmul


## Zaključne pripombe 


<br>
Zgoraj opisan postopek omogoča klasifikacijo stanja na podlagi Jordanovega razcepa matrike. 


Izbrane opombe:
- Ker je Jordanov razcep numerično zelo občutljiv, je izvedljiv samo v okviru simboličnega računanja. Tu Python ni najboljši in zgoraj naveden razcep sem opravil v programskem paketu Wolfram Mathematica. V omejenem okviru je dostopen tudi spletno: https://www.wolframalpha.com/input/?i=jordan+normal+form+calculator
- Če lastne vrednosti prehodne matrike $P$ niso med sabo vse različne, Jordanov razcep še vedno obstaja, a Jordanova matrika $J$ ni več diagonalna. Tedaj se zgornji razmislek nekoliko zaplete, a je še vedno izvedljiv. 

<p style="margin-bottom:2cm;"></p>
<div style="width:100%;text-align:right;font-weight:bold;font-size:1.2em;"> 2 </div>
<img src="https://raw.githubusercontent.com/andrejkk/ORvTK_SlidesImgs/master/footer_full.jpg">
